--- # Fast Start :: Problem Diagnosis and Troubleshooting Lab 
--- # Deployment with corrected syntax, the - (single dash) on the name of containers:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pink-baker
  namespace: pink
  labels:
    app: pink-baker
spec:
  selector:
    matchLabels:
      app: pink-baker
  replicas: 1
  template:
    metadata:
      labels:
        app: pink-baker
    spec:
      containers:
        name: pink-baker
        image: ibmicpcoc/baker:latest
        imagePullPolicy: Always
        env:
          - name: APP_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: COLLECTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: pink-collector-config
                key: COLLECTOR_CONFIG
          - name: INSTRUCTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: pink-collector-config
                key: INSTRUCTOR_CONFIG
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
---
    